### ISSUE TITLE
風をシミュレーションする

### ISSUE THREAD

**Issue by toru-naka** [seal-git/menubar_furin#4]

**Comment by toru-naka** [comment]
立式してもらったものを実装する

**Comment by toru-naka** [comment]
![20220804風鈴](https://user-images.githubusercontent.com/60499202/183226778-158d555c-ceb6-45a2-be03-cbd5c5d7f81b.jpg)

**Comment by milmilmilk** [comment]
跳ね返り係数の設定と、短冊の角度がまだなので、少し待ってください

**Comment by tnakai11** [comment]
https://github.com/seal-git/menubar_furin/issues/18 に isuue を分離
